# Generated by Django 5.2.1 on 2025-05-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=20)),
                ('size', models.CharField(choices=[('S', 'シングル'), ('W', 'ダブル')], max_length=2)),
                ('container', models.CharField(choices=[('cup', 'カップ'), ('cone', 'コーン')], max_length=10)),
                ('flavor1', models.CharField(choices=[('jersey', 'ジャージー牛乳'), ('matcha', '抹茶'), ('mango', 'マンゴー'), ('mint', 'チョコミント'), ('blackbean', '黒豆'), ('saltcaramel', '塩キャラ'), ('strawberry', 'いちご'), ('strawmilk', 'いちごミルク'), ('idashio', '井田塩'), ('cassis', 'カシス'), ('chocolat', 'ショコラ'), ('sakura', 'さくらもち')], max_length=50)),
                ('flavor2', models.CharField(blank=True, choices=[('jersey', 'ジャージー牛乳'), ('matcha', '抹茶'), ('mango', 'マンゴー'), ('mint', 'チョコミント'), ('blackbean', '黒豆'), ('saltcaramel', '塩キャラ'), ('strawberry', 'いちご'), ('strawmilk', 'いちごミルク'), ('idashio', '井田塩'), ('cassis', 'カシス'), ('chocolat', 'ショコラ'), ('sakura', 'さくらもち')], max_length=50, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ok', 'アイス作成OK'), ('stop', 'アイス作成STOP'), ('hold', '保留（非表示待ち）')], default='ok', max_length=10)),
                ('clip_color', models.CharField(choices=[('yellow', '黄色'), ('white', '白色')], max_length=10)),
                ('clip_number', models.IntegerField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_stopped', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_pudding', models.BooleanField(default=False, verbose_name='アフォガードプリン')),
            ],
        ),
    ]
