# Generated by Django 5.2.1 on 2025-06-01 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='flavor1',
            field=models.CharField(choices=[('jersey', 'ジャージー牛乳'), ('matcha', '抹茶'), ('mango', 'マンゴー'), ('mint', 'チョコミント'), ('blackbean', '黒豆'), ('saltcaramel', '塩キャラ'), ('strawberry', 'いちご'), ('strawmilk', 'いちごミルク'), ('idashio', '井田塩'), ('cassis', 'カシス'), ('chocolat', 'ショコラ'), ('sakura', 'さくらもち'), ('coffee', 'コーヒー'), ('lemon', 'レモン'), ('hojicha', 'ほうじ茶'), ('yuzu', 'ゆず')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='flavor2',
            field=models.CharField(blank=True, choices=[('jersey', 'ジャージー牛乳'), ('matcha', '抹茶'), ('mango', 'マンゴー'), ('mint', 'チョコミント'), ('blackbean', '黒豆'), ('saltcaramel', '塩キャラ'), ('strawberry', 'いちご'), ('strawmilk', 'いちごミルク'), ('idashio', '井田塩'), ('cassis', 'カシス'), ('chocolat', 'ショコラ'), ('sakura', 'さくらもち'), ('coffee', 'コーヒー'), ('lemon', 'レモン'), ('hojicha', 'ほうじ茶'), ('yuzu', 'ゆず')], max_length=50, null=True),
        ),
    ]
