# Generated by Django 5.2.1 on 2025-07-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice', '0002_alter_order_flavor1_alter_order_flavor2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'かき氷注文', 'verbose_name_plural': 'かき氷注文'},
        ),
        migrations.AlterField(
            model_name='order',
            name='flavor1',
            field=models.CharField(choices=[('jersey', 'ジャージー牛乳'), ('matcha', '抹茶'), ('mango', 'マンゴー'), ('mint', 'チョコミント'), ('blackbean', '黒豆'), ('saltcaramel', '塩キャラ'), ('strawberry', 'いちご'), ('strawmilk', 'いちごミルク'), ('idashio', '井田塩'), ('cassis', 'カシス'), ('chocolat', 'ショコラ'), ('sakura', 'さくらもち'), ('coffee', 'コーヒー'), ('lemon', 'レモン'), ('hojicha', 'ほうじ茶'), ('yuzu', 'ゆず'), ('ume', 'ウメ')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='flavor2',
            field=models.CharField(blank=True, choices=[('jersey', 'ジャージー牛乳'), ('matcha', '抹茶'), ('mango', 'マンゴー'), ('mint', 'チョコミント'), ('blackbean', '黒豆'), ('saltcaramel', '塩キャラ'), ('strawberry', 'いちご'), ('strawmilk', 'いちごミルク'), ('idashio', '井田塩'), ('cassis', 'カシス'), ('chocolat', 'ショコラ'), ('sakura', 'さくらもち'), ('coffee', 'コーヒー'), ('lemon', 'レモン'), ('hojicha', 'ほうじ茶'), ('yuzu', 'ゆず'), ('ume', 'ウメ')], max_length=50, null=True),
        ),
    ]
