# Generated by Django 5.2.1 on 2025-07-18 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice', '0003_alter_order_options_alter_order_flavor1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'アイスクリーム注文', 'verbose_name_plural': 'アイスクリーム注文'},
        ),
    ]
