# Generated by Django 5.2.1 on 2025-07-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice', '0004_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='flavor1',
            field=models.CharField(choices=[('jersey', 'ジャージー牛乳'), ('ocha', 'お茶'), ('mango', 'マンゴー'), ('mint', 'チョコミント'), ('caramel', 'キャラメル'), ('strawberry', 'いちご'), ('tachibana', 'たちばな'), ('idashio', '井田塩'), ('cassis', 'カシス'), ('chocolate', 'ショコラ'), ('coffee', 'コーヒー'), ('lemon', 'レモン')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='flavor2',
            field=models.CharField(blank=True, choices=[('jersey', 'ジャージー牛乳'), ('ocha', 'お茶'), ('mango', 'マンゴー'), ('mint', 'チョコミント'), ('caramel', 'キャラメル'), ('strawberry', 'いちご'), ('tachibana', 'たちばな'), ('idashio', '井田塩'), ('cassis', 'カシス'), ('chocolate', 'ショコラ'), ('coffee', 'コーヒー'), ('lemon', 'レモン')], max_length=50, null=True),
        ),
    ]
