# Generated by Django 5.2.6 on 2025-09-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice', '0005_alter_order_flavor1_alter_order_flavor2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-timestamp'], 'verbose_name': 'アイスクリーム注文', 'verbose_name_plural': 'アイスクリーム注文'},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'is_completed'], name='ice_status_completed_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['clip_color', 'clip_number'], name='ice_clip_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['group_id'], name='ice_group_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['timestamp'], name='ice_timestamp_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['size', 'is_completed'], name='ice_size_completed_idx'),
        ),
    ]
