# Generated by Django 5.2.1 on 2025-11-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice', '0006_alter_order_options_order_ice_status_completed_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status_modified_at'], name='ice_status_modified_idx'),
        ),
    ]
