# Generated by Django 5.2.1 on 2025-05-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShavedIceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(choices=[('いちご', 'いちご'), ('ゆず', 'ゆず'), ('ほうじ茶', 'ほうじ茶'), ('抹茶', '抹茶')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=100)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
