# Generated by Django 5.2.1 on 2025-06-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shavedice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shavediceorder',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='shavediceorder',
            name='quantity',
        ),
        migrations.AddField(
            model_name='shavediceorder',
            name='clip_color',
            field=models.CharField(choices=[('yellow', '黄色'), ('white', '白色')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='shavediceorder',
            name='clip_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shavediceorder',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shavediceorder',
            name='flavor',
            field=models.CharField(choices=[('抹茶', '抹茶'), ('いちご', 'いちご'), ('ゆず', 'ゆず'), ('ほうじ茶', 'ほうじ茶')], max_length=50),
        ),
        migrations.AlterField(
            model_name='shavediceorder',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
