# Generated by Django 5.2.1 on 2025-07-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shavedice', '0002_rename_created_at_shavediceorder_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shavediceorder',
            options={'verbose_name': 'かき氷注文', 'verbose_name_plural': 'かき氷注文'},
        ),
        migrations.AddField(
            model_name='shavediceorder',
            name='group_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shavediceorder',
            name='is_auto_stopped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shavediceorder',
            name='status',
            field=models.CharField(choices=[('ok', 'アイス作成OK'), ('stop', 'アイス作成STOP'), ('hold', '保留（非表示待ち）')], default='ok', max_length=10),
        ),
    ]
