# Generated by Django 5.2.1 on 2025-07-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shavedice', '0003_alter_shavediceorder_options_shavediceorder_group_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shavediceorder',
            name='flavor',
            field=models.CharField(choices=[('抹茶', '抹茶'), ('いちご', 'いちご'), ('ゆず', 'ゆず')], max_length=50),
        ),
    ]
