# Generated by Django 5.2.6 on 2025-09-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shavedice', '0004_alter_shavediceorder_flavor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shavediceorder',
            options={'ordering': ['-timestamp'], 'verbose_name': 'かき氷注文', 'verbose_name_plural': 'かき氷注文'},
        ),
        migrations.AddIndex(
            model_name='shavediceorder',
            index=models.Index(fields=['status', 'is_completed'], name='shavedice_status_completed_idx'),
        ),
        migrations.AddIndex(
            model_name='shavediceorder',
            index=models.Index(fields=['clip_color', 'clip_number'], name='shavedice_clip_idx'),
        ),
        migrations.AddIndex(
            model_name='shavediceorder',
            index=models.Index(fields=['group_id'], name='shavedice_group_idx'),
        ),
        migrations.AddIndex(
            model_name='shavediceorder',
            index=models.Index(fields=['timestamp'], name='shavedice_timestamp_idx'),
        ),
        migrations.AddIndex(
            model_name='shavediceorder',
            index=models.Index(fields=['flavor', 'is_completed'], name='shavedice_flavor_completed_idx'),
        ),
    ]
