# Generated by Django 5.2.1 on 2025-11-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shavedice', '0005_alter_shavediceorder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shavediceorder',
            name='status_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shavediceorder',
            name='flavor',
            field=models.CharField(choices=[('🍧いちご🍧', '🍧いちご🍧'), ('🍧抹茶🍧', '🍧抹茶🍧'), ('🍧ほうじ茶🍧', '🍧ほうじ茶🍧'), ('🍧ゆず🍧', '🍧ゆず🍧')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='shavediceorder',
            index=models.Index(fields=['status_modified_at'], name='shavedice_status_modified_idx'),
        ),
    ]
