# Generated by Django 5.2.1 on 2025-05-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'シングル'), ('W', 'ダブル')], max_length=1)),
                ('container', models.CharField(choices=[('cup', 'カップ'), ('cone', 'コーン')], max_length=10)),
                ('flavor1', models.CharField(choices=[('jersey', 'ジャージー牛乳'), ('matcha', '抹茶'), ('mango', 'マンゴー')], max_length=20)),
                ('flavor2', models.CharField(blank=True, choices=[('jersey', 'ジャージー牛乳'), ('matcha', '抹茶'), ('mango', 'マンゴー')], max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
