# Generated by Django 5.2.1 on 2025-05-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iceorder',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
