# Generated by Django 5.2.1 on 2025-05-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_iceorder_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='iceorder',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
