# Generated by Django 5.2.1 on 2025-05-09 12:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_iceorder_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='iceorder',
            name='order_group',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36),
        ),
    ]
