# Generated by Django 5.2.1 on 2025-05-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_iceorder_order_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=20)),
                ('size', models.CharField(choices=[('S', 'シングル'), ('W', 'ダブル')], max_length=2)),
                ('container', models.CharField(choices=[('cup', 'カップ'), ('cone', 'コーン')], max_length=10)),
                ('flavor1', models.CharField(max_length=50)),
                ('flavor2', models.CharField(blank=True, max_length=50, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ok', 'アイス作成OK'), ('stop', 'アイス作成STOP'), ('hold', '保留（非表示待ち）')], default='ok', help_text='デシャップ用：アイス作成許可状態', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='IceOrder',
        ),
    ]
