# Generated by Django 5.2.1 on 2025-05-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_delete_iceorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='flavor1',
            field=models.CharField(choices=[('jersey', 'ジャージー牛乳'), ('matcha', '抹茶'), ('mango', 'マンゴー'), ('mint', 'チョコミント'), ('blackbean', '黒豆'), ('saltcaramel', '塩キャラ'), ('strawberry', 'いちご'), ('strawmilk', 'いちごミルク'), ('idashio', '井田塩'), ('cassis', 'カシス'), ('chocolat', 'ショコラ'), ('sakura', 'さくらもち')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='flavor2',
            field=models.CharField(blank=True, choices=[('jersey', 'ジャージー牛乳'), ('matcha', '抹茶'), ('mango', 'マンゴー'), ('mint', 'チョコミント'), ('blackbean', '黒豆'), ('saltcaramel', '塩キャラ'), ('strawberry', 'いちご'), ('strawmilk', 'いちごミルク'), ('idashio', '井田塩'), ('cassis', 'カシス'), ('chocolat', 'ショコラ'), ('sakura', 'さくらもち')], max_length=50, null=True),
        ),
    ]
