# Generated by Django 5.2.1 on 2025-05-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_flavor1_alter_order_flavor2'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='clip_color',
            field=models.CharField(choices=[('yellow', '黄色'), ('white', '白色')], default='yellow', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='clip_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ok', 'アイス作成OK'), ('stop', 'アイス作成STOP'), ('hold', '保留（非表示待ち）')], default='ok', max_length=10),
        ),
    ]
