# Generated by Django 5.2.1 on 2025-05-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_auto_stopped',
            field=models.BooleanField(default=False),
        ),
    ]
