# Generated by Django 5.2.1 on 2025-05-15 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_is_auto_stopped'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_pudding',
            field=models.BooleanField(default=False, verbose_name='アフォガードプリン'),
        ),
    ]
