# Generated by Django 5.2.1 on 2025-05-16 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('clip_color', models.CharField(max_length=10)),
                ('clip_number', models.IntegerField()),
                ('group_id', models.CharField(max_length=50)),
                ('status', models.CharField(default='ok', max_length=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
