# Generated by Django 5.2.1 on 2025-05-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
