# Generated by Django 5.2.1 on 2025-07-18 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_foodorder_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodorder',
            options={'verbose_name': 'フード注文', 'verbose_name_plural': 'フード注文'},
        ),
    ]
