# Generated by Django 5.2.1 on 2025-07-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_foodorder_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='eat_in',
            field=models.BooleanField(default=True),
        ),
    ]
