# Generated by Django 5.2.1 on 2025-07-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_foodorder_eat_in'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodorder',
            options={'ordering': ['-timestamp'], 'verbose_name': 'フード注文', 'verbose_name_plural': 'フード注文'},
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='clip_color',
            field=models.CharField(help_text='オーダー表のクリップの色（yellow, white等）', max_length=10, verbose_name='クリップ色'),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='clip_number',
            field=models.IntegerField(help_text='オーダー表のクリップの番号（1-16等）', verbose_name='クリップ番号'),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='注文が完了した時刻（完了時に設定）', null=True, verbose_name='完了時刻'),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='eat_in',
            field=models.BooleanField(default=True, help_text='True=店内飲食、False=テイクアウト', verbose_name='店内飲食'),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='group_id',
            field=models.CharField(help_text='同一注文グループを識別するID（複数商品の一括注文用）', max_length=50, verbose_name='グループID'),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='注文が完了したかどうかのフラグ', verbose_name='完了フラグ'),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='menu',
            field=models.CharField(help_text='注文されたフードのメニュー名（例：からあげ丼、ルーロー飯）', max_length=20, verbose_name='メニュー名'),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='note',
            field=models.TextField(blank=True, default='', help_text='注文に関する特記事項や要望', verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='注文数量（1以上の整数）', verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='status',
            field=models.CharField(default='ok', help_text='注文の現在の状態（ok=作成OK、stop=STOP中）', max_length=10, verbose_name='注文状態'),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='注文を受けた時刻（自動設定）', verbose_name='受注時刻'),
        ),
    ]
