# Generated by Django 5.2.6 on 2025-09-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_foodorder_options_alter_foodorder_clip_color_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='foodorder',
            index=models.Index(fields=['status', 'is_completed'], name='food_status_completed_idx'),
        ),
        migrations.AddIndex(
            model_name='foodorder',
            index=models.Index(fields=['clip_color', 'clip_number'], name='food_clip_idx'),
        ),
        migrations.AddIndex(
            model_name='foodorder',
            index=models.Index(fields=['timestamp'], name='food_timestamp_idx'),
        ),
        migrations.AddIndex(
            model_name='foodorder',
            index=models.Index(fields=['group_id'], name='food_group_idx'),
        ),
        migrations.AddIndex(
            model_name='foodorder',
            index=models.Index(fields=['menu', 'is_completed'], name='food_menu_completed_idx'),
        ),
    ]
